research_task:
  description: >
    Accept user input specifying the commodity (e.g., wheat, rice) and the {topic} (e.g., "new policies," "climate impact on crops").
    Use the Google Serper tool to perform searches for the most relevant articles related to the {topic}.
    Retrieve and rank up to 10 articles based on relevance and publication date.
    Provide the following for each article:
      - Headline
      - Full URL to the article
      - Brief content snippet or summary
  expected_output: >
    A ranked list of up to 10 articles related to the {topic}, including:
      - Headline
      - Full URL to the article
      - Brief summary of each article
  agent: researcher

reporting_task:
  description: >
    Analyze each article fetched by the Researcher Agent based on the {topic}.
    Perform sentiment analysis, assigning a score from -5 to +5 to each article to reflect its potential impact on the commodity price:
      - Positive (surge): Score > 0
      - Negative (drop): Score < 0
      - Neutral: Score = 0
    Aggregate and summarize the results:
      - Total count of positive, negative, and neutral articles.
      - Insights on the overall sentiment regarding the {topic}.
    Present a final report including actionable insights.
  expected_output: >
    For each article:
      - Headline
      - Summary
      - Sentiment score
      - Full URL
    Aggregate Summary:
      - Total number of articles by sentiment (positive, negative, neutral)
      - Insights on the overall trend for the commodity price regarding the {topic}.

    Formatted as markdown without '```'
  agent: reporting_analyst
