research_task:
  description: >
    Find out the latest policy changes, updates and reports on the commodity {topic} in India from the past month.
    Look for the most recent Indian articles that might affect the commodity prices, prioritizing news from the last 30 days.
    Retrieve and rank up to 10 articles based on publication date (most recent first), relevance, and reliability.
    For each article, include its URL for reference.
    Provide the following details for each article:
      - Headline
      - Brief content snippet summarizing the article
      - Publication date
      - Source URL
  expected_output: >
    A ranked list of up to 8 articles related to the {topic}, including:
      - Headline: Title of the article
      - Summary: 2 to 3 sentence summary
      - Source: Website or publication name
      - Date: Publication date
      - URL: Direct link to the article
  agent: researcher

reporting_task:
  expected_output: >
    The final report should be in markdown format and include the following sections:

    # Top 10 Relevant Articles

    ### 1. **Govt Raises MSP for Wheat**
    
    The government has announced an increase in the minimum support price (MSP) for wheat to ₹2,200 per quintal. This move is expected to benefit farmers but may lead to a price surge in open markets.
    
    - **Sentiment Score:** +3
    - *Source:* The Hindu
    - *Date:* 2024-03-15
    - *URL:* [Read full article](https://example.com/article-url)

    ### 2. **Rainfall Deficit May Impact Rice Exports**
    
    Below-average rainfall in key rice-producing states such as Punjab and Haryana may result in lower exports, affecting both global and domestic markets.
    
    - **Sentiment Score:** -2
    - *Source:* Economic Times
    - *Date:* 2024-03-14
    - *URL:* [Read full article](https://example.com/article-url)
  agent: reporting_analyst